export const GET_PARENT_CATEGORY_WITH_CHILDS = 'GET_PARENT_CATEGORY_WITH_CHILDS';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const ADD_CATEGORY = 'ADD_CATEGORY'
export const GET_CATEGORY = 'GET_CATEGORY'
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY'