export const ADD_PRODUCT = 'ADD_PRODUCT';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_MY_PRODUCTS = 'GET_MY_PRODUCTS';
export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_PRODUCT_BY_CATEGORY_ID = 'GET_PRODUCT_BY_CATEGORY_ID';