export const ADD_CURRENCY_UNIT = 'ADD_CURRENCY_UNIT';
export const GET_CURRENCY_UNITS = 'GET_CURRENCY_UNITS'
export const UPDATE_CURRENCY_UNIT = 'UPDATE_CURRENCY_UNIT'
export const GET_CURRENCY_UNIT = 'GET_CURRENCY_UNIT'